### ISSUE TITLE
Directed edges

### ISSUE THREAD

**Issue by JPWeir** [JPWeir/Graf#41]
Investigate links in Vue/D3 Networks, find out how to optionally style edges to be nondirectional, directed, and bidirected.
Probably won't be fully implemented/functional until we have the [Expanded Toolbar](https://github.com/JPWeir/Graf/issues/6) finished.

**Comment by N-Desmarais** [comment]
Added in 163beb2934f1cfef0b7a9407e22e6c9055f8fe6a
