### ISSUE TITLE
Select and Move Nodes

### ISSUE THREAD

**Issue by JPWeir** [JPWeir/Graf#5]
When using the select tool, left clicking individual nodes should select only that node. Holding shift or ctrl and left clicking further nodes should add them to the selection. Users should also be able to left click & drag a selection box to select several nodes.
When a user left clicks and drags a node, it should move the node and any other selected nodes.

**Comment by JPWeir** [comment]
Moving nodes seems trivial with D3 networks, but we'll still want to be able to select and move multiple nodes.

**Comment by JPWeir** [comment]
Selected nodes should be highlighted in a distinct color.

**Comment by N-Desmarais** [comment]
moving selected node coloring to a different issue
