### ISSUE TITLE
Expanded Toolbar

### ISSUE THREAD

**Issue by JPWeir** [JPWeir/Graf#6]
We want to allow users to select what kind of edge or node they're placing. There's two approaches we could go with here:
1. When either the node or edge tool is right clicked, you can pull up several options (such as different colors for nodes/edges, or directed edges for the edge tool.)
2. When mousing over the node or edge tool, a drop down menu expands. From here the user could select options like described above.

I'm not entirely set on either of these options, so feel free to investigate and decide what you find feasible.

**Comment by JPWeir** [comment]
We're leaning towards a drop down menu when you hover over a tool, if feasible. Alternatively we could still go with a drop down on left/right click, but hover would probably be more intuitive.

**Comment by N-Desmarais** [comment]
Added sub menu functionality too Toolbar.vue in d91b038f1cdac7170e604afaf9df73a4268b1c79.
